# You will want to fill this out for each run, it should be fine to clone this repo for each run.
type: 'meta_t' # type can be 'meta_t' or 'meta_g'
inputs:
  interleaved_reads:
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/altamaha_2019_sw_WHONDRS-S19S_0010_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/arikareeriver_2019_sw_WHONDRS-S19S_0023_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/augustacreek_2019_sw_WHONDRS-S19S_0067_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/blackearthcreek_2019_sw_WHONDRS-S19S_0061_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/blackwarrior_2019_sw_WHONDRS-S19S_0021_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/blueriver_2019_sw_WHONDRS-S19S_0024_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/blythe_2019_sw_WHONDRS-S19S_0092_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/cachelapoudre_2019_sw_WHONDRS-S19S_0072_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/cariboucreek_2019_sw_WHONDRS-S19S_0051_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/cartcreek_2019_sw_WHONDRS-S19S_0073_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/cobbmillcreek_2019_sw_WHONDRS-S19S_0090_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/columbia_2019_sw_WHONDRS-S19S_0036_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/columbia_2019_sw_WHONDRS-S19S_0074_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/columbiariver2_2019_sw_WHONDRS-S19S_0076_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/comocreek_2019_sw_WHONDRS-S19S_0026_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/deadrun_2019_sw_WHONDRS-S19S_0006_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/dobsoncreek_2019_sw_WHONDRS-S19S_0087_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/eastforkpoplarcreek_2019_sw_WHONDRS-S19S_0039_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/farmington_2019_sw_WHONDRS-S19S_0053_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/fraser_2019_sw_WHONDRS-S19S_0001_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/greatmiami_2019_sw_WHONDRS-S19S_0099_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/guil_2019_sw_WHONDRS-S19S_0049_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/gunnisonriver_2019_sw_WHONDRS-S19S_0062_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/hugercreek_2019_sw_WHONDRS-S19S_0044_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/icacos_2019_sw_WHONDRS-S19S_0094_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/king_2019_sw_WHONDRS-S19S_0016_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/kingscreed_2019_sw_WHONDRS-S19S_0040_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/lajara_2019_sw_WHONDRS-S19S_0034_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/littlewindriver_2019_sw_WHONDRS-S19S_0009_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/littlewolfcreek_2019_sw_WHONDRS-S19S_0078_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/logan1_2019_sw_WHONDRS-S19S_0097_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/logan2_2019_sw_WHONDRS-S19S_0098_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/lowercolorado_2019_sw_WHONDRS-S19S_0063_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/marshallgulch_2019_sw_WHONDRS-S19S_0035_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/marthacreek_2019_sw_WHONDRS-S19S_0030_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/mcdi_2019_sw_WHONDRS-S19S_0017_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/middleoconee_2019_sw_WHONDRS-S19S_0011_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/morescreek_2019_sw_WHONDRS-S19S_0085_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/muddycreek_2019_sw_WHONDRS-S19S_0082_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/nakdong_2019_sw_WHONDRS-S19S_0056_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/nebranchanacostia_2019_sw_WHONDRS-S19S_0081_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/oksrukuyikcreek_2019_sw_WHONDRS-S19S_0050_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/orco_2019_sw_WHONDRS-S19S_0096_MT_trimmed.anqrpht.fastq
     - /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/pamunkeyriver_2019_sw_WHONDRS-S19S_0054_MT_trimmed.anqrpht.fastq
  paired_reads:
  named_reads:
  # Here you can put nothing, or asmany reads as you want with the format: 
  #   any_name_you_want: 
  #     R1: /home/ORG-Data-2/EMERGE/2016_27metaT/3_E1D_Daly_pool_1_S3_L001_R1_001.fastq.gz
  #     R2: /home/ORG-Data-2/EMERGE/2016_27metaT/3_E1D_Daly_pool_1_S3_L001_R2_001.fastq.gz
  #     inter: /home/ORG-Data-2/EMERGE/2016_27metaT/3_E1D_Daly_pool_1_S3_L001_001.fastq.gz
    pamunkeyriver_2019_sw_WHONDRS-S19S_0054_MT_trimmed.anqrpht:
      inter: /home/projects-wrighton-2/GROWdb/USAfocus_FinalBins110121/dereplicated_bin_analyses/metaT_mapping/bowtie_mapping_final/pamunkeyriver_2019_sw_WHONDRS-S19S_0054_MT_trimmed.anqrpht.fastq
  # This is one database file should it be more?
  # You set both the input and output for the database, that bowtie2 will use. These files may be used for many
  # analisies so the output file can be in a central location so it dose not need to be remade. 
  bowtie2_database_raw: /home/projects-wrighton/EMERGE/EMERGE_metaTs/2016/concat_mapping/97dRep_scaffolds_combined.fa
  bowtie2_database_built: resources/bowtie2_databases/full_db
  # bowtie2_database_raw:  test_data/vari_size_inputs/database_3412_size.fa
  # bowtie2_database_built: resources/bowtie2_databases/database_3412_cores_10
  gff: /home/projects-wrighton/EMERGE/EMERGE_metaTs/2016/concat_mapping/drep_genes_combined.gff
# You will probably not use this part 75% of the time.
outputs:
  get_quality: False
  get_counts: True
  get_stats: False
  get_bams: True 
binning:
  forward_id: '_1'
  backward_id: '_2'
  sickle_quality_type: 'sanger' # options inclued 'sanger' and 'illumina' 
coverm:
  min_read_percent_identity_pair: 0.95,
  min_covered_fraction: 0.75
  min_depth: 3
  genome_fasta_extension: 'fa'
counting:
  percent_read: 95 # For Rich sam_file.py: percent of (read_length - mismatches)/read_length to keep EX: 90
  max_mismatch: 3 # For Rich sam_file.py: max number of mismatches
  featuretype: 'CDS' # For workflow/scripts/flexcount.py: Feature type (3rd column in GTF file) to be used, all features of other type are ignored
  idattr: 'ID' # For workflow/scripts/flexcount.py: GTF attribute to be used as feature ID (default, suitable for Ensembl GTF files: gene_id). 
backend:
  report: "report/workflow.rst"
  check_fasta_for_dups: True


